### ISSUE TITLE
The merged entity couldn't be updated to DB

### ISSUE THREAD

**Issue by vinkii** [nfrpaiva/ui-merge#1]
As the title mentioned, the merged entity will lost the "managed status", so it won't be updated to db.

**Comment by nfrpaiva** [comment]
The primary objective is use a incomplete object came from view to pass values to a object managed. But just pass values that you mark with annotation. Then you can use the merge but not managed object to persist.
When I construct this I think it's help to work with spring objects from view but after some searchs now I prefer put managed object in session and usa a session complet after update ou persist data.
So I think this is not so useful as i think...

**Comment by vinkii** [comment]
Thanks for your reply. Now I merge my entity manually.
